/*******************************************************************************
THIS PROGRAM IS FREE SOFTWARE. YOU CAN REDISTRIBUTE IT AND/OR MODIFY IT
UNDER THE TERMS OF THE GNU GPLV3 AS PUBLISHED BY THE FREE SOFTWARE FOUNDATION.

Copyright (C), 2016-2016, Team MicroDynamics <microdynamics@126.com>

Filename:    stm32f10x_driver_spi.c
Author:      maksyuki
Version:     0.1.0.20161231_release
Create date: 2016.08.14
Description: Implement the SPI bus operation function
Others:      none
Function List:
             1. void SPI_InitSPI(void);
             2. void SPI_InitSPI1(void);
             3. u8   SPI_ReadAndWrite(u8 byte);
History:
<author>    <date>        <desc>
maksyuki    2016.11.30    Modify the module
myyerrol    2017.04.23    Format the module
*******************************************************************************/

#include "stm32f10x_driver_spi.h"

void SPI_InitSPI(void)
{
    SPI_InitSPI1();
}

void SPI_InitSPI1(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;
    SPI_InitTypeDef  SPI_InitStructure;

    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB, ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_SPI1, ENABLE);

    // Configure the pins SCK, MISO and MOSI of the NRF24L01.
    GPIO_InitStructure.GPIO_Pin   = GPIO_Pin_5 | GPIO_Pin_6 | GPIO_Pin_7;
    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_AF_PP;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_10MHz;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    // Configure the pins CE, CSN of the NRF24L01.
    GPIO_InitStructure.GPIO_Pin   = GPIO_Pin_12;
    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_Out_PP;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_10MHz;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    GPIO_InitStructure.GPIO_Pin   = GPIO_Pin_4;
    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_Out_PP;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_10MHz;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    SPI_CSN_H();

    // Two lines fullduplex.
    SPI_InitStructure.SPI_Direction         = SPI_Direction_2Lines_FullDuplex;
    // Master.
    SPI_InitStructure.SPI_Mode              = SPI_Mode_Master;
    // 8 bits.
    SPI_InitStructure.SPI_DataSize          = SPI_DataSize_8b;
    // Clock polarity, floor time is low.
    SPI_InitStructure.SPI_CPOL              = SPI_CPOL_Low;
    // First edge is valid, the first edge is sampling time.
    SPI_InitStructure.SPI_CPHA              = SPI_CPHA_1Edge;
    // NSS sign is generated by software.
    SPI_InitStructure.SPI_NSS               = SPI_NSS_Soft;
    // 8 frequency division, 9MHz.
    SPI_InitStructure.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_8;
    // MSB.
    SPI_InitStructure.SPI_FirstBit          = SPI_FirstBit_MSB;
    // CRC polynomial is 7.
    SPI_InitStructure.SPI_CRCPolynomial     = 7;
    SPI_Init(SPI1, &SPI_InitStructure);

    SPI_Cmd(SPI1, ENABLE);
}

u8 SPI_ReadAndWrite(u8 byte)
{
    while (SPI_I2S_GetFlagStatus(SPI1, SPI_I2S_FLAG_TXE) == RESET);
    SPI_I2S_SendData(SPI1, byte);
    while (SPI_I2S_GetFlagStatus(SPI1, SPI_I2S_FLAG_RXNE) == RESET);

    return SPI_I2S_ReceiveData(SPI1);
}
