/*******************************************************************************
THIS PROGRAM IS FREE SOFTWARE. YOU CAN REDISTRIBUTE IT AND/OR MODIFY IT 
UNDER THE TERMS OF THE GNU GPLV3 AS PUBLISHED BY THE FREE SOFTWARE FOUNDATION.

Copyright (C), 2016-2016, Team MicroDynamics <microdynamics@126.com>

Filename:    stm32f10x_driver_spi.c
Author:      maksyuki
Version:     0.1.0.20161231_release
Create date: 2016.8.14
Description: implement the SPI bus operation function
Others:      none
Function List:
             1. void SPI_INIT(void);
             2. u8 SPI_RW(u8 data);
History:
1. <author>    <date>         <desc>
   maksyuki  2016.11.30  modify the module
*******************************************************************************/

#include "stm32f10x_driver_spi.h"

void SPI_INIT(void)
{
    SPI_InitTypeDef SPI_InitStructure;
    GPIO_InitTypeDef GPIO_InitStructure;

    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB, ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_SPI1, ENABLE);

    /* Configure the pins SCK, MISO and MOSI of the SPI_NRF_SPI with GPIOA^5, GPIOA^6 and GPIOA^7 */
    GPIO_InitStructure.GPIO_Pin   = GPIO_Pin_5 | GPIO_Pin_6 | GPIO_Pin_7;
    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_AF_PP;  /* Multiplexing function */
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_10MHz;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    /* Configure the pins CE of the SPI_NRF_SPI and the pin CSN of the SPI_NRF_SPI */
    /* NRF_CE--PA12 */
    GPIO_InitStructure.GPIO_Pin   = GPIO_Pin_12;
    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_Out_PP;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_10MHz;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    /* NRF_CSN--PA4 */
    GPIO_InitStructure.GPIO_Pin   = GPIO_Pin_4;
    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_Out_PP;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_10MHz;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    SPI_CSN_H();

    SPI_InitStructure.SPI_Direction         = SPI_Direction_2Lines_FullDuplex; /* Two lines fullduplex */
    SPI_InitStructure.SPI_Mode              = SPI_Mode_Master;                 /* Master */
    SPI_InitStructure.SPI_DataSize          = SPI_DataSize_8b;                 /* 8 bits */
    SPI_InitStructure.SPI_CPOL              = SPI_CPOL_Low;                    /* Clock polarity, floor time is low */
    SPI_InitStructure.SPI_CPHA              = SPI_CPHA_1Edge;                  /* First edge is valid, the rising edge is sampling time */
    SPI_InitStructure.SPI_NSS               = SPI_NSS_Soft;                    /* NSS sign is generated by software */
    SPI_InitStructure.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_8;         /* 8 frequency division, 9MHz */
    SPI_InitStructure.SPI_FirstBit          = SPI_FirstBit_MSB;                /* MSB */
    SPI_InitStructure.SPI_CRCPolynomial     = 7;
    SPI_Init(SPI1, &SPI_InitStructure);

    /* Enable SPI1 */
    SPI_Cmd(SPI1, ENABLE);
}

u8 SPI_RW(u8 data)
{
    while (SPI_I2S_GetFlagStatus(SPI1, SPI_I2S_FLAG_TXE) == RESET);
    SPI_I2S_SendData(SPI1, data);
    while (SPI_I2S_GetFlagStatus(SPI1, SPI_I2S_FLAG_RXNE) == RESET);
    return SPI_I2S_ReceiveData(SPI1); 
}
